### ISSUE TITLE
config_app.exe don't run on Windows 11 64bit

### ISSUE THREAD

**Issue by viper-666** [rnd-ash/ultimate_nag52#15]
Hello Ashcon,
unfortunately the latest config_app.exe you provide over the Telegram group don't work on my system. It starts and a second after the start windows will show it crashed.
So I compiled the rust version on my system, but I have a lot of warnings while the compiling process and after run the compiled config_app.exe it crashed again after a second but this time I can see a error message: "(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)".
Here I have put the status messages while compiling: [https://pastebin.com/4zBu6qZx](url)

**Comment by rnd-ash** [comment]
> Hello Ashcon,
> unfortunately the latest config_app.exe you provide over the Telegram group don't work on my system. It starts and a second after the start windows will show it crashed.
> So I compiled the rust version on my system, but I have a lot of warnings while the compiling process and after run the compiled config_app.exe it crashed again after a second but this time I can see a error message: "(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)".
> Here I have put the status messages while compiling: [https://pastebin.com/4zBu6qZx](url)
> 

I've tested the latest git in my windows 10 VM, and it works fine.

Can you provide more details about your system?

I'll try and get a win11 VM for further testing next week!

**Comment by viper-666** [comment]
![image](https://user-images.githubusercontent.com/13709294/211252366-bb4d5056-437a-41e0-b510-fb474ee5fa5f.png)

Older versions from the config_app.exe you postet earlier works on my system.

**Comment by viper-666** [comment]
The newest release work with my Windows 11 so I closed this issue.
