### ISSUE TITLE
does SH8KA4TB1 need a diode to drive solenoids?

### ISSUE THREAD

**Issue by rusefillc** [rnd-ash/ultimate_nag52#6]
Do you have/need flyback (?) diodes if using SH8KA4TB1 to drive solenoids?

![image](https://user-images.githubusercontent.com/48498823/162590448-d696d4b8-23f4-4586-bd2a-ee6ef3133971.png)

**Comment by rnd-ash** [comment]
This doesn't look like my tcm, rather I think the one in your image is SSCG's one (standalone without can)

That said, my circuits use a MOSFET and diode, using the exact same setup as the OEM EGS53 TCM (even as far as to use the same automotive grade BUK9277 MOSFETs) . Electrically, it is extremely stable at any pwm (0-4096), and I have not noticed any issues with this circuit in my board I've been using for just under a year now.

**Comment by rusefillc** [comment]
Oooops :)
