### ISSUE TITLE
config_app unable to compile

### ISSUE THREAD

**Issue by borgonzola** [rnd-ash/ultimate_nag52#7]
Compiling ecu_diagnostics v0.90.33
error[E0432]: unresolved import `j2534_rust::Loggable`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ecu_diagnostics-0.90.33/src/hardware/passthru/mod.rs:36:40
   |
36 |     ConnectFlags, FilterType, IoctlID, Loggable, PassthruError, Protocol, RxFlag, TxFlag,
   |                                        ^^^^^^^^ no `Loggable` in the root
   
   
   This issue also appears trying to build cloned ecu_diagnostics.

**Comment by rnd-ash** [comment]
fixed and closed
